In [ ]:
## text genertion with hugging face
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
prompt= "what is machine learning"
output =pipe(prompt)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
print(output[0]["generated_text"])

what is machine learning now?

Machine learning, as it's known, is being used by AI researchers as a tool to identify, identify and measure behavior in humans. It is a very powerful tool, but it's also very hard to get right. If you want to find out if you are the first to respond to a call, you need to know what kind of person you are. We don't want to be left guessing. We want to find out what kind of person is the first to respond to a call. It's the same with machine learning.

I think it's really important that we see this as a tool for the future.

You mentioned I did that the big challenge for machine learning is not just how do we get to the information we want. The big challenge is how do we build a society where all the people are going to the same place and all of them are going to be able to meet the same obligations as everyone else.

Machine learning is an incredibly powerful tool, but it is very hard to get right.

When did you start using machine learning?

I started using it while I was at Stanford. I was a scientist, and I was working on the computer science curriculum. I didn't really know what

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM


tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [ ]:
sentence="unsure"
input_ids=tokenizer(sentence,return_tensors="pt")["input_ids"]
input_ids

tensor([[13271,   495]])

In [ ]:
tokenizer.decode(input_ids[0])

'unsure'

In [ ]:
sentence="unbelivable"
input_ids=tokenizer(sentence,return_tensors="pt")["input_ids"]

In [ ]:
input_ids

tensor([[  403,  6667, 21911]])

In [ ]:
for token_ids in input_ids[0]:
  print(tokenizer.decode(token_ids))

un
bel
ivable

In [ ]:
word="computer science"
my_ids=tokenizer(word,return_tensors="pt").input_ids
my_ids

tensor([[33215,  3783]])

In [ ]:
tokenizer.decode(my_ids.squeeze())

'computer science'

In [ ]:
word="pneumonoultramicroscopicsilicovolcanoconiosis"
my_ids=tokenizer(word,return_tensors="pt").input_ids
my_ids

tensor([[   79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]])

In [ ]:
for token_id in my_ids[0]:
  print(tokenizer.decode(token_id))

p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis

In [ ]:
sentence="Antidisestablishmentarianism"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids
token_ids

tensor([[13217, 29207, 44390,  3699,  1042]])

In [ ]:
word="Floccinaucinihilipilification"
my_ids=tokenizer(word,return_tensors="pt").input_ids
my_ids

tensor([[ 7414, 13966,   259, 14272,   259, 20898,   541,   346,  2649]])

In [ ]:
for token_ids in my_ids.squeeze():
  print(tokenizer.decode(token_ids))

Fl
occ
in
auc
in
ihil
ip
il
ification

In [ ]:
gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
gpt2

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [ ]:
sentence="I love machine learning,but I 'm not sure if I can do it in a way that's as good as it could be."
token_ids=tokenizer(sentence,return_tensors="pt").input_ids
token_ids
output=gpt2(token_ids).logits[0,-1]
tokenizer.decode(output.argmax())

'.'

In [ ]:
sentence="I love dance and songs because they're so simple and they're so simple."
token_ids=tokenizer(sentence,return_tensors="pt").input_ids

outputs=gpt2(token_ids).logits[0,-1]
tokenizer.decode(outputs.argmax())

'.'

In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
sentence="I learn machine learning"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits[0,-1]
final_logits=torch.topk(outputs,5)


for index in final_logits.indices:
  print(tokenizer.decode(index))

 is
 from
 in
 and
,

In [ ]:
torch.softmax(final_logits.values,dim=0).sum()

tensor(1.0000, grad_fn=<SumBackward0>)

In [ ]:
final_logits.values.sum()

tensor(-426.3003, grad_fn=<SumBackward0>)

In [ ]:
def greedy_decode(logits):

  return torch.argmax(logits,dim=-1)
tokenizer.decode(greedy_decode(outputs))

' learning'

In [ ]:
def tok_k_sampling(logits,k=50):
  """
  keeps inly top k logits.normalize them into probablilty.
  them sample one token from the filtered distribution
  """
  values,indices=torch.topk(logits,k)
  probs=F.softmax(values,dim=-1)
  sampled=torch.multinomial(probs,1)
  return indices[sampled]

def top_p_sampling(logits,p=0.9):
  """sort tokens by prob. keep smallest number whose cumulative prob
  exceeds treshold p, then sample one token"""

  sorted_logits,sorted_indices=torch.sort(logits,descending=True)
  sorted_probs=F.softmax(sorted_logits,dim=-1)
  cumulative_probs=sorted_probs.cumsum(dim=-1)


  mask = cumulative_probs > p
  sorted_logits[mask] = float("-inf")
  filtered_probs=F.softmax(sorted_logits,dim=-1)
  sampled=torch.multinomial(filtered_probs,1)
  return sorted_indices[sampled]

In [ ]:
tokenizer.decode(tok_k_sampling(outputs))

' learning'

In [ ]:
outputs

tensor([-92.1910, -90.4428, -96.6676,  ..., -98.7475, -99.8798, -94.4455],
       grad_fn=<SelectBackward0>)

In [ ]:
tokenizer.decode(top_p_sampling(outputs,p=0.9))

' learning'

In [ ]:
#temp sampling

def temperature_sampling(logits,temperature=1.0):
  """
  scale logits by temperature before sampling
  lower temperature values - sharper probability distribution
  higher temperture values -flatened " "

  """

  scaled=logits/temperature
  probs=F.softmax(scaled,dim=-1)
  return torch.multinomial(probs,1)

In [ ]:
temperature_sampling(outputs,temperature=0.9)

tensor([422])

In [ ]:
tokenizer.decode(temperature_sampling(outputs,temperature=1.3))

' coming'

In [ ]:
def random_sampling(logits):
   """
   sample directly from softmax distribution without any filtering
   """
   probs=F.softmax(logits,dim=-1)
   return torch.multinomial(probs,1)

In [ ]:
random_sampling(outputs)

tensor([2427])

In [ ]:
tokenizer.decode(random_sampling(outputs))

' from'

In [ ]:
sentence="I am really happy because every"
inputs=tokenizer(sentence,return_tensors="pt")
outputs=gpt2(**inputs)
logits=outputs.logits[0,-1]

print(f"greedy decode ",tokenizer.decode([greedy_decode(logits)]))
print(f"top k samplimng ",tokenizer.decode(tok_k_sampling(logits,k=10)))
print(f"top p sampling ",tokenizer.decode(top_p_sampling(logits,p=0.9)))
print(f"temp ",tokenizer.decode(temperature_sampling(logits,temperature=0.7)))
print(f"randon ",tokenizer.decode(random_sampling(logits)))

greedy decode   time
top k samplimng   day
top p sampling   time
temp   effort
randon   time

In [ ]:
sentence="I learn machine learning to enhance a"
token_ids=tokenizer(sentence,return_tensors="pt").input_ids
outputs=gpt2(token_ids).logits

outputs=torch.softmax(outputs[0,-1],dim=-1)
top10=torch.topk(outputs,k=10)
for index,value in zip(top10.indices,top10.values):
  print(f"{tokenizer.decode(index)}--{value:.1%}")
outputs

 user--5.3%
 person--3.3%
 lot--1.8%
 computer--1.5%
 particular--1.5%
 human--1.4%
 product--1.3%
 machine--1.1%
 variety--1.0%
 given--0.9%

tensor([1.0790e-06, 7.7912e-06, 1.5296e-07,  ..., 7.0506e-09, 1.7039e-08,
        3.0795e-06], grad_fn=<SoftmaxBackward0>)

In [ ]:
##sentiment analysis

In [ ]:
from datasets import load_dataset

ds = load_dataset("stanfordnlp/imdb")

In [ ]:
type(ds)

datasets.dataset_dict.DatasetDict

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [ ]:
ds["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [ ]:
import pandas as pd

In [ ]:
ds["train"].to_pandas()

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [ ]:
my_dataset_df=ds["train"].to_pandas()

In [ ]:
my_dataset_df["text"]

0        I rented I AM CURIOUS-YELLOW from my video sto...
1        "I Am Curious: Yellow" is a risible and preten...
2        If only to avoid making this type of film in t...
3        This film was probably inspired by Godard's Ma...
4        Oh, brother...after hearing about this ridicul...
                               ...
24995    A hit at the time but now better categorised a...
24996    I love this movie like no other. Another time ...
24997    This film and it's sequel Barry Mckenzie holds...
24998    'The Adventures Of Barry McKenzie' started lif...
24999    The story centers around Barry McKenzie who mu...
Name: text, Length: 25000, dtype: object

In [ ]:
len(my_dataset_df["text"])

25000

In [ ]:
from transformers import pipeline

In [ ]:
classifier=pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [ ]:
classifier("this day is great")

[{'label': 'POSITIVE', 'score': 0.9998873472213745}]

In [ ]:
classifier("this day is so bad")

[{'label': 'NEGATIVE', 'score': 0.9998189806938171}]

In [ ]:
def score(review_text):
  return classifier(review_text[:500])[0]["label"]

In [ ]:
my_dataset_df["model_prediction"] = my_dataset_df["text"].apply(score)
"""
what this will do is it will give give a new column to the dataset called model-prediction and write "postive " and "negative"
"""

KeyboardInterrupt:

In [ ]:
my_dataset_df

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [ ]:
my_dataset_df[["label","model_prediction"]][:20]

In [ ]:
print(my_dataset_df.iloc[0]["text"])
classifier(review)
classifer(review)[0]

In [ ]:
from transformers import pipeline

In [ ]:
finbert =pipeline("sentiment-analysis",model="ProsusAI/finbert")

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
sentence="price is higher than cost"
finbert(sentence)

[{'label': 'neutral', 'score': 0.8101989030838013}]

In [ ]:
sentence="shares fail after the firm repoted lower than expected earnings"
finbert(sentence)

[{'label': 'negative', 'score': 0.9484241604804993}]

In [ ]:
sentences=["strong consumer demand frove record sales across all regions",
           "supply chain disruptions severly affected production output"]
finbert(sentences)

[{'label': 'positive', 'score': 0.950765073299408},
 {'label': 'negative', 'score': 0.9608097672462463}]

In [ ]:
#named entity recongnition

sentence="Apple announced earnings in  the United States on Sunday "

In [ ]:
ner=pipeline("ner")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [ ]:
ner(sentence)

[{'entity': 'I-ORG',
  'score': np.float32(0.99909294),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5},
 {'entity': 'I-LOC',
  'score': np.float32(0.999681),
  'index': 6,
  'word': 'United',
  'start': 33,
  'end': 39},
 {'entity': 'I-LOC',
  'score': np.float32(0.9995665),
  'index': 7,
  'word': 'States',
  'start': 40,
  'end': 46}]

In [ ]:
SENTENCE="I worker at Facebook after graduation form St.Joseph college in Pala"
ner(SENTENCE)

[{'entity': 'I-ORG',
  'score': np.float32(0.9940771),
  'index': 4,
  'word': 'Facebook',
  'start': 12,
  'end': 20},
 {'entity': 'I-LOC',
  'score': np.float32(0.58367157),
  'index': 8,
  'word': 'St',
  'start': 43,
  'end': 45},
 {'entity': 'I-LOC',
  'score': np.float32(0.7488065),
  'index': 10,
  'word': 'Joseph',
  'start': 46,
  'end': 52},
 {'entity': 'I-LOC',
  'score': np.float32(0.9853843),
  'index': 13,
  'word': 'Pa',
  'start': 64,
  'end': 66},
 {'entity': 'I-LOC',
  'score': np.float32(0.97371393),
  'index': 14,
  'word': '##la',
  'start': 66,
  'end': 68}]

In [ ]:
#question ans

In [ ]:
qa_bot=pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
context="""
RAM (Random Access Memory) is a computer's high-speed, short-term memory that
temporarily stores data for active applications and the operating system. It

allows the processor to access information instantly, enabling smooth multitasking and faster performance.
 RAM is volatile, meaning it loses all stored data when the device is powered off.
 Purpose: It acts as a workspace for the CPU, holding data from currently running applications to prevent slow access from permanent storage (HDD/SSD).
Volatility: Unlike a hard drive, RAM requires electricity to keep data; turning off the computer clears it.
Performance Impact: More RAM allows a computer to handle more tasks simultaneously without lagging.
Types: Modern computers typically use DDR4 or DDR5 SDRAM, which are fast and efficient.
Location: Installed as memory modules (DIMMs) in slots on the computer's motherboard
"""

In [ ]:
question="what is RAM"

In [ ]:
qa_bot(question=question,context=context)

{'score': 0.5763823986053467, 'start': 274, 'end': 282, 'answer': 'volatile'}

In [ ]:
question="what are we using RAM?"

In [ ]:
result=qa_bot(question=question,context=context)

In [ ]:
print(result["answer"])

a computer's high-speed, short-term memory

In [ ]:
#machine translation

In [ ]:
from transformers import MarianMTModel, MarianTokenizer

model_name = "Helsinki-NLP/opus-mt-en-fr"
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)


# → "Bonjour, comment allez-vous ?"

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

In [ ]:
text = ["Hello, how are you?"]
tokens = tokenizer(text, return_tensors="pt", padding=True)
translated = model.generate(**tokens)

print(tokenizer.decode(translated[0], skip_special_tokens=True))

Bonjour, comment allez-vous ?